In [2]:
import numpy as np



## Numpy
- Work well arrays
- The perfomance its fast, as it uses C language
- Statistical Oriented -mean,mode and std
- Open Source Library

## Shortcuts
- Run ctrl+alt+enter

In [9]:
marks = np.array([90,10,23,44,98])
marks3 = [2,3,4]
marks3 = map(lambda x:x*2,marks3)
print(list(marks3))
print(marks3) #This will repeats the List twice, but with numpy is different
#[2, 3, 4, 2, 3, 4]
print(marks*2)
#array([180,  20,  46,  88, 196])

[4, 6, 8]
[180  20  46  88 196]


In [10]:
#Create a lrge array
np.ones(200)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.arange(10)
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
#get some booleans and stuff
np.arange(10)*2
all10 = np.arange(10)
allGrt5 = np.arange(10) >5
print(allGrt5)

##Filetring
print(all10[allGrt5])
#Same as 
print(all10[all10>5])

[False False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]


## Task 01
Create a 1..200 numbers and provide a numpy array with all even numbers

In [20]:
nums = np.arange(1,200)
numsEven = nums[nums%2==0]
print(numsEven)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [46]:
#Some randoming stuff
ages = np.random.randint(18,60,100)
#will create from 18, to 60 , 5 values

#Can you get like distict values though
# Shuffle the array to get distinct random values
agesDistict = np.random.shuffle(ages)
print(agesDistict)
#Creating a list
ages_list =ages.tolist()
print(ages_list)

None
[56, 43, 38, 50, 46, 45, 32, 48, 55, 36, 32, 38, 54, 28, 23, 52, 38, 25, 57, 39, 48, 32, 53, 39, 25, 29, 42, 19, 51, 56, 35, 25, 19, 46, 50, 32, 41, 35, 24, 18, 32, 58, 35, 40, 36, 46, 53, 24, 25, 27, 20, 59, 53, 52, 27, 38, 37, 48, 55, 23, 46, 24, 59, 42, 27, 44, 24, 31, 49, 44, 58, 36, 43, 28, 35, 32, 47, 56, 54, 31, 51, 25, 57, 49, 49, 25, 19, 22, 24, 28, 46, 22, 48, 24, 44, 51, 24, 37, 36, 30, 20, 35, 39, 23, 49, 29, 48, 39, 18, 28, 34, 37, 19, 49, 29, 36, 45, 18, 43, 54, 48, 45, 33, 42, 35, 37, 37, 55, 45, 19, 51, 26, 27, 41, 18, 30, 58, 29, 29, 49, 33, 54, 57, 19, 31, 36, 35, 40, 43, 59, 51, 29, 42, 54, 43, 32, 26, 33, 18, 29, 59, 42, 51, 22, 27, 54, 20, 48, 39, 46, 57, 54, 41, 49, 21, 44, 25, 36, 41, 46, 19, 19, 39, 19, 35, 20, 22, 49, 57, 19, 20, 50, 52, 35, 20, 35, 54, 25, 20, 26, 33, 33, 54, 54, 46, 46, 24, 51, 54, 49, 57, 19, 46, 47, 25, 39, 31, 53, 53, 57, 44, 25, 52, 30, 34, 44, 45, 52, 29, 32, 30, 36, 44, 29, 34, 25, 54, 56, 28, 23, 18, 52, 21, 53, 50, 35, 18, 27, 44

In [47]:
%%time
double_ages = [age * 2 for age in ages_list]
print(double_ages)

[112, 86, 76, 100, 92, 90, 64, 96, 110, 72, 64, 76, 108, 56, 46, 104, 76, 50, 114, 78, 96, 64, 106, 78, 50, 58, 84, 38, 102, 112, 70, 50, 38, 92, 100, 64, 82, 70, 48, 36, 64, 116, 70, 80, 72, 92, 106, 48, 50, 54, 40, 118, 106, 104, 54, 76, 74, 96, 110, 46, 92, 48, 118, 84, 54, 88, 48, 62, 98, 88, 116, 72, 86, 56, 70, 64, 94, 112, 108, 62, 102, 50, 114, 98, 98, 50, 38, 44, 48, 56, 92, 44, 96, 48, 88, 102, 48, 74, 72, 60, 40, 70, 78, 46, 98, 58, 96, 78, 36, 56, 68, 74, 38, 98, 58, 72, 90, 36, 86, 108, 96, 90, 66, 84, 70, 74, 74, 110, 90, 38, 102, 52, 54, 82, 36, 60, 116, 58, 58, 98, 66, 108, 114, 38, 62, 72, 70, 80, 86, 118, 102, 58, 84, 108, 86, 64, 52, 66, 36, 58, 118, 84, 102, 44, 54, 108, 40, 96, 78, 92, 114, 108, 82, 98, 42, 88, 50, 72, 82, 92, 38, 38, 78, 38, 70, 40, 44, 98, 114, 38, 40, 100, 104, 70, 40, 70, 108, 50, 40, 52, 66, 66, 108, 108, 92, 92, 48, 102, 108, 98, 114, 38, 92, 94, 50, 78, 62, 106, 106, 114, 88, 50, 104, 60, 68, 88, 90, 104, 58, 64, 60, 72, 88, 58, 68, 50, 108,

## Stats stuff
- mean
- mode
- median
They shouw use the outlier, that can scared

In [48]:
np.median(marks)

38.0

In [49]:
np.sum(marks)

265

## Task
invest = 1000
intRate = 0.5
year = 2

In [81]:
invest = 1000
OriginalValue = 1000
intRate = 0.05

inYear = [ invest := invest+invest*intRate for i in range(10) ]
print(inYear)
#After Ten years
print(inYear[9])
#Task 03
diff = inYear[-1] - OriginalValue
diff_perce = (diff/invest)*100
print(f'{diff_perce:.2f}%')
print(round(diff_perce,2),"%",sep="")
invest

[1050.0, 1102.5, 1157.625, 1215.50625, 1276.2815624999998, 1340.0956406249998, 1407.1004226562497, 1477.4554437890622, 1551.3282159785153, 1628.894626777441]
1628.894626777441
38.61%
38.61%


1628.894626777441

In [69]:
#Task 02
years = np.arange(1, 11)
yearly_return = 1000 * 1.05 ** years
print(yearly_return.tolist())

[1050.0, 1102.5, 1157.6250000000002, 1215.5062500000001, 1276.2815625000003, 1340.0956406250004, 1407.1004226562504, 1477.455443789063, 1551.3282159785163, 1628.894626777442]


# After Break

In [90]:
salary = np.random.randint(1_000,100_000,10)
print(salary)

#The Mean anf the max
print(np.max(salary))


#To get the index using argmax()
print(np.argmax(salary))

[67568  2131 83122 99439  7731 88868 93846 97797 94524 61689]
99439
3


### Unique
will give the unique values of the Numpy
Get the data, will work for nums and strings

In [93]:
#Unique
nums = np.random.randint(1,4,10)
nums
np.unique(nums)

array([1, 2, 3])

### Cleaning

In [97]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
np.char.title(items)
np.char.strip(items)

array(['Apple', 'banana', 'GRAPE', 'cucumber', 'Pineapple', 'tomato',
       'Orange', 'lemon', 'Kiwi', 'mango', 'blueberry', 'raspberry'],
      dtype='<U10')

#### Task 01

In [99]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
items = np.unique(items)
items = np.char.lower(items)
items = np.char.strip(items)
items

array(['apple', 'lemon', 'raspberry', 'tomato', 'grape', 'kiwi', 'orange',
       'pineapple', 'banana', 'blueberry', 'cucumber', 'mango'],
      dtype='<U10')

#### Task 02

In [107]:
#a
NewItemsBool = np.char.startswith(items,'b')
NewItems = items[NewItemsBool]
print(NewItems)

#b
NewItemsBool2 = np.char.find(items,'b') != -1
NewItems2 = items[NewItemsBool2]
print(NewItems2)

['banana' 'blueberry']
[False False  True False False False False False  True  True  True False]
['raspberry' 'banana' 'blueberry' 'cucumber']


#### Taks 03

In [110]:

hourly_visitors = [468, 279, 73, 272, 406 ,128, 302, 216, 140,  82]
lis = np.array(hourly_visitors)

# Total visitors
total = np.sum(lis)
print(total)
#peak Hour
peak = np.argmax(lis)+1
print(f"{peak} hour")
#On Average peopl visist
ave = np.average(lis)
print(ave)

2366
1 hours
236.6


### 2d Array

In [118]:
matrix = np.array([[1,2,3],
                   [6,10,17],
                   [9,20,24]])
matrix.shape
np.sum(matrix)
#Numpy was made to work with multi dimention things


92

In [119]:
np.sum(matrix,0)

array([16, 32, 44])

In [117]:
np.sum(np.sum(matrix,0))

92

In [120]:
#adding to the Arraya
matrix + 1

array([[ 2,  3,  4],
       [ 7, 11, 18],
       [10, 21, 25]])

USing reshape to put into a steps

In [122]:
stats = np.random.randint(40,100,9)
print(stats)
#Then we Reshape
stats3 = stats.reshape(3,3)
print(stats3)

[94 79 82 53 59 82 94 55 66]
[[94 79 82]
 [53 59 82]
 [94 55 66]]


#### Task


In [127]:
sensor1 = np.array([[23, 25, 22],
                    [20, 21, 20],
                    [26, 25, 24]])
sensor2 = np.array([[24, 23, 24],
                    [22, 22, 23],
                    [25, 26, 26]])

Average = (sensor1 + sensor2)/2
print(Average)

[[23.5 24.  23. ]
 [21.  21.5 21.5]
 [25.5 25.5 25. ]]


### Task 2:
Find the averge temp given 


In [129]:
AveSens1 = np.average(sensor1,1)
print(AveSens1)
AveSens2 = np.average(sensor2,1)
print(AveSens2)

[23.33333333 20.33333333 25.        ]
[23.66666667 22.33333333 25.66666667]


### Task 03

In [131]:
AveSens1 = np.average(sensor1,0)
print(AveSens1)
AveSens2 = np.average(sensor2,0)
print(AveSens2)

[23.         23.66666667 22.        ]
[23.66666667 23.66666667 24.33333333]
